// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-section-chat-header'
  | 'item-section-chat-sidenav'
  | 'pref-apiKey'
  | 'pref-apiUrl'
  | 'pref-enable'
  | 'pref-fullTextLimit'
  | 'pref-help'
  | 'pref-model'
  | 'pref-prompt-explain'
  | 'pref-prompt-translate'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
