// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiUrl": string;
      "apiKey": string;
      "model": string;
      "promptTranslate": string;
      "promptExplain": string;
      "fullTextLimit": number;
    };
  }
}
